### ISSUE TITLE
Concerning Commit 484e5d

### ISSUE THREAD

**Issue by Kaayy-J** [doe300/OHMComm#23]
Commit 484e5d97178bc55020bc3ff5236a785cb4c15b44
Is not compiling because winsock2.h is included more than one time.

It is included in
- NetworkWrapper.cpp (we agreed that the methods getLastError() and closeSocket() does not belong to NetworkWrapper but rather to UDPWrapper didnt we?)
- RTPListener.h (Everything related to Network should be either in NetworkWrapper (if general information) or in UDPWrapper (if UDP-related information) )

**Comment by Kaayy-J** [comment]
@doe300 
Ping Pong ;).

**Comment by doe300** [comment]
Should be fixed now via 9ab487cafd2b97a423f59f4db563b15264cad4e2 . Needs some testing though!

**Comment by Kaayy-J** [comment]
@doe300 In configuration.h it must be
_WIN32
not
__WIN32
Therefore your bugfix is not really a bugfix, because compile errors still exists.

Error reason is
/\* Prevent inclusion of winsock.h in windows.h */

**Comment by Kaayy-J** [comment]
Solved by commit commit f7cea4eafac16dab9f1dd6084e28c44765b4b20d
